version: "3"
services:
  duckhunt:
    image: registry.gitlab.com/tstark2/duckhunt:1.0
    tty: true
    stdin_open: true
    container_name: duckhunt
    volumes:
      - /var/www/duckHunt/static:/go/static
networks: 
  default:
    external:
      name: "duckhunt"